### ISSUE TITLE
Invalid `--uses-next-auth` cli option

### ISSUE THREAD

**Issue by yunsii** [iiian/prisma-case#60]
https://github.com/iiian/prisma-case-format/blob/fbdb03fd56f01ee5195ce9b1cfd7f7b7a616b5f0/src/cli.ts#L50

Call `ConventionStore.fromFile` without `options.usesNextAuth`.

https://github.com/iiian/prisma-case-format/blob/fbdb03fd56f01ee5195ce9b1cfd7f7b7a616b5f0/src/convention-store.ts#L84-L92
https://github.com/iiian/prisma-case-format/blob/fbdb03fd56f01ee5195ce9b1cfd7f7b7a616b5f0/src/convention-store.ts#L99-L104

`fromFile` and `fromCon` do not process `usesNextAuth`. I can create a PR if possible.

**Comment by iiian** [comment]
> I can create a PR if possible.

Yes, please! Thanks, @yunsii!
